core: add support for internal device factories

diff --git a/src/tests/Makefile.am b/src/tests/Makefile.am
--- a/src/tests/Makefile.am
+++ b/src/tests/Makefile.am
@@ -95,3 +95,19 @@ TESTS = \
 	test-general-with-expect \
 	test-wired-defname
 
+
+if ENABLE_TESTS
+
+check-local:
+	@for t in ; do \
+		# Ensure the device subclass factory registration constructors exist \
+		# which could inadvertently break if src/Makefile.am gets changed \
+		if ! LC_ALL=C nm $(top_builddir)/src/NetworkManager | LC_ALL=C grep -q "register_device_factory_internal_$$t" ; then \
+			echo "Testing device factory symbols... FAILED" ; \
+			exit 1 ; \
+		fi \
+	done
+	@echo -n "Testing device factory symbols... PASSED"
+
+endif
+
