build: add test for valid po files (msgfmt -vc)
(cherry picked from commit 97c1bed37e46906f5450f53333e903c679f47ffe)

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -5260,6 +5260,20 @@ include Makefile.examples
 
 ###############################################################################
 
+check-po-msgfmt:
+	@echo "check-po-msgfmt: check $(top_srcdir)/po/*.po files with msgfmt -vc"
+	@for f in "$(top_srcdir)/po"/*.po ; do \
+		if ! msgfmt -vc "$$f" &>/dev/null ; then \
+			echo "invalid po file: msgfmt -vc $$f" ; \
+			msgfmt -vc "$$f" ; \
+			exit 1 ; \
+		fi ; \
+	done
+
+check_local += check-po-msgfmt
+
+###############################################################################
+
 check-local: $(check_local)
 
 dist-hook: $(dist_hook)
