build: fix test for valid po files (msgfmt -vc)
Otherwise, the test generates an "messages.mo" file.

Fixes: 97c1bed37e46 ('build: add test for valid po files (msgfmt -vc)')
(cherry picked from commit ad55cf86e89a2a03e938f9374f481aa5d94bd40a)
(cherry picked from commit 9b5ef3aaea5be298bf2ae6bd588b130d6ff756bd)

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -5173,9 +5173,9 @@ include Makefile.examples
 check-po-msgfmt:
 	@echo "check-po-msgfmt: check $(top_srcdir)/po/*.po files with msgfmt -vc"
 	@for f in "$(top_srcdir)/po"/*.po ; do \
-		if ! msgfmt -vc "$$f" &>/dev/null ; then \
-			echo "invalid po file: msgfmt -vc $$f" ; \
-			msgfmt -vc "$$f" ; \
+		if ! msgfmt -vc "$$f" -o /dev/null &>/dev/null ; then \
+			echo "invalid po file: msgfmt -vc $$f -o /dev/null" ; \
+			msgfmt -vc "$$f" -o /dev/null ; \
 			exit 1 ; \
 		fi ; \
 	done
