libnm-glib: libnm_glib -> libnm-glib
Bothered me for a long time; now that we've bumped the soname, we can
rename the library too.

diff --git a/policy/Makefile.am b/policy/Makefile.am
--- a/policy/Makefile.am
+++ b/policy/Makefile.am
@@ -5,19 +5,20 @@ dist_polkit_policy_DATA = $(dist_polkit_policy_in_files:.policy.in=.policy)
 
 @INTLTOOL_POLICY_RULE@
 
-check:
-	@for f in $(dist_polkit_policy_DATA); do \
-            echo -n "Validate PolicyKit policy in $$f : "; \
-            $(POLKIT_POLICY_FILE_VALIDATE) $(srcdir)/$$f ; \
-	    ret=$$?; \
-            if  [ "$$ret" = "0" ]; \
-	      then \
-                echo ok; \
-            else \
-                echo failed; \
-		exit 1; \
-            fi; \
-        done;
+# polkit >= 0.92 doesn't have an updated polkit-policy-file-validate
+#check:
+#	@for f in $(dist_polkit_policy_DATA); do \
+#            echo -n "Validate PolicyKit policy in $$f : "; \
+#            $(POLKIT_POLICY_FILE_VALIDATE) $(srcdir)/$$f ; \
+#	    ret=$$?; \
+#            if  [ "$$ret" = "0" ]; \
+#	      then \
+#                echo ok; \
+#            else \
+#                echo failed; \
+#		exit 1; \
+#            fi; \
+#        done;
 
 clean-local :
 	rm -f *~
